# Site settings
title: Cory Klein Blog
email: cory@coryklein.com
description: > # this means to ignore newlines until "baseurl:"
    Cory Klein blogs about technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coryklein.com" # the base hostname & protocol for your site
twitter_username: coryfklein
github_username:  coryfklein

# Build settings
markdown: kramdown
